name: QA Test Suite

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    smoke-tests:
        name: Smoke Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run smoke tests
              uses: cypress-io/github-action@v6
              with:
                spec: 'cypress/e2e/smoke/**/*.cy.ts'

            - name: Upload Cypress screenshots on failure
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: smoke-screenshots
                path: cypress/screenshots

    regression-tests:
        name: Regression Tests
        runs-on: ubuntu-latest
        needs: smoke-tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run regression tests
              uses: cypress-io/github-action@v6
              with:
                spec: 'cypress/e2e/regression/**/*.cy.ts' 

            - name: Upload regression screenshots on failure
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: regression-screenshots 
                path: cypress/screenshots

           

    postman-tests:
        name: Postman API Tests
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Newman
          run: npm install -g newman

        - name: Run Postman collection
          run: newman run "postman/SauceDemo API Tests.postman_collection.json"

            